export const ADD_ITEM_LIST = 'ADD ITEM LIST'
export const DELETE_ITEM_LIST = 'DELETE ITEM LIST'
export const DELETE_ITEMS_TO_DO_LIST = 'DELETE ITEMS TO DO LIST'
export const ADD_ITEM_TO_DO_LIST = 'ADD ITEM TO DO LIST'